# Generated by Django 5.2.7 on 2026-05-21 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0008_interviewbooking_proposed_availability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('INTERVIEWER_NO_SHOW', 'Interviewer never joined'), ('CANDIDATE_NO_SHOW', 'Candidate never joined'), ('ENDED_TOO_EARLY', 'Interview ended too early'), ('UNPROFESSIONAL', 'Unprofessional behavior'), ('LOW_QUALITY', 'Poor interview quality'), ('POOR_FEEDBACK', 'Poor feedback quality'), ('ABUSE', 'Abusive behavior'), ('TECHNICAL', 'Technical issue'), ('PAYMENT', 'Payment concern'), ('OTHER', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('WAITING_FOR_RESPONSE', 'Waiting For Response'), ('ACTION_TAKEN', 'Action Taken'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='OPEN', max_length=50)),
                ('resolution', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('issue_deadline', models.DateTimeField(blank=True, null=True)),
                ('candidate_presence_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('interviewer_presence_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('against_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_against', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bookings.interviewbooking')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'UNDER_REVIEW', 'WAITING_FOR_RESPONSE', 'ACTION_TAKEN'])), fields=('booking', 'raised_by'), name='unique_active_issue_per_user_per_booking')],
            },
        ),
    ]
