# Generated by Django 5.2.7 on 2025-12-17 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Include country code', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('years_of_interview_experience', models.PositiveIntegerField(default=0)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('specializations', models.JSONField(default=list, help_text="Example: ['Frontend', 'Backend', 'System Design']")),
                ('languages', models.JSONField(default=list, help_text="Example: ['English', 'Hindi']")),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('github_url', models.URLField(blank=True, max_length=300)),
                ('portfolio_url', models.URLField(blank=True, max_length=300)),
                ('expertise_summary', models.TextField(help_text='Short summary of interviewer’s experience and strengths.')),
                ('motivation', models.TextField(blank=True, help_text='Why do you want to be an interviewer?')),
                ('resume', models.FileField(upload_to='interviewers/resumes/')),
                ('certifications', models.FileField(blank=True, null=True, upload_to='interviewers/certifications/')),
                ('additional_docs', models.FileField(blank=True, null=True, upload_to='interviewers/additional_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_interviewer_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The normal user who applied to become an interviewer.', on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interviewer Application',
                'verbose_name_plural': 'Interviewer Applications',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_interviewer_application_per_user')],
            },
        ),
    ]
