# Generated by Django 5.2.7 on 2025-12-25 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('headline', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(max_length=1000)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='interviewers/profile_pictures/')),
                ('years_of_experience', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('specializations', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('industries', models.JSONField(blank=True, default=list)),
                ('is_profile_public', models.BooleanField(default=False)),
                ('is_accepting_bookings', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_step', models.CharField(choices=[('PROFILE', 'Profile'), ('AVAILABILITY', 'Availability'), ('VERIFICATION', 'Verification'), ('COMPLETED', 'Completed')], default='PROFILE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text='e.g. Passport, Aadhaar, Driving License', max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_file', models.FileField(upload_to='interviewer_verification/')),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interviewer Verification',
                'verbose_name_plural': 'Interviewer Verifications',
            },
        ),
        migrations.CreateModel(
            name='InterviewerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which this availability applies')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', help_text='Timezone of the interviewer', max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_type', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], max_length=10, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, help_text='End date for recurring availability', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('interviewer', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
