# Generated by Django 5.2.7 on 2026-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0002_interviewerprofile_interviewerverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweravailability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intervieweravailability',
            name='max_bookings',
            field=models.PositiveIntegerField(default=1, help_text='Maximum bookings allowed for this availability'),
        ),
    ]
