# Generated by Django 5.2.7 on 2026-01-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0003_intervieweravailability_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweravailability',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intervieweravailability',
            name='reschedule_reason',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='intervieweravailability',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
