# Generated by Django 5.2.7 on 2026-04-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0004_intervieweravailability_reschedule_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerapplication',
            name='company_name',
            field=models.CharField(blank=True, help_text='Current or most recent company the applicant works/worked at.', max_length=200),
        ),
    ]
