# Generated by Django 5.2.7 on 2026-05-29 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0005_interviewerapplication_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerprofile',
            name='base_session_rate',
            field=models.PositiveIntegerField(default=10, help_text='Token cost for a 30-minute session', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
