# Generated by Django 5.2.7 on 2026-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0006_interviewerprofile_base_session_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweravailability',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes'), (90, '90 minutes')], default=30, help_text='Session duration in minutes. Must be 30, 45, 60, or 90.'),
        ),
    ]
