# Generated by Django 5.2.7 on 2026-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0007_add_duration_minutes_to_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerprofile',
            name='supported_experience_levels',
            field=models.JSONField(blank=True, default=list, help_text='Experience levels this interviewer is comfortable conducting. Valid values: BEGINNER, INTERMEDIATE, ADVANCED'),
        ),
        migrations.AddField(
            model_name='interviewerprofile',
            name='supported_interview_types',
            field=models.JSONField(blank=True, default=list, help_text='List of interview type keys this interviewer supports. Valid values: TECHNICAL, BEHAVIORAL, HR_ROUND, CODING, MOCK_FULL, RESUME_REVIEW, WARMUP, SYSTEM_DESIGN'),
        ),
    ]
