# Generated by Django 5.2.7 on 2026-01-09 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_inr', models.PositiveIntegerField(help_text='Price in INR')),
                ('tokens', models.PositiveIntegerField(help_text='Tokens credited')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_inr'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_inr__gt', 0)), name='price_positive'), models.CheckConstraint(condition=models.Q(('tokens__gt', 0)), name='tokens_positive')],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_inr', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CREATED', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('internal_order_id', models.CharField(blank=True, help_text='Stable internal ID for frontend tracking', max_length=50, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
                ('token_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.tokenpack')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='payments_pa_user_id_201308_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_71e312_idx'), models.Index(fields=['stripe_checkout_session_id'], name='payments_pa_stripe__0aeb93_idx'), models.Index(fields=['internal_order_id'], name='payments_pa_interna_3738e1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_inr__gt', 0)), name='amount_positive')],
            },
        ),
    ]
