# Generated by Django 5.2.7 on 2026-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpack',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
