# Generated by Django 5.2.7 on 2026-06-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_tokenpack_is_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenpack',
            name='is_purchased',
        ),
    ]
