"""
Django settings for intraview project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from decimal import Decimal
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
import cloudinary
import dj_database_url


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")


# Application definition

INSTALLED_APPS = [
    'cloudinary',
    'cloudinary_storage',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'django_filters',
    'authentication',
    'interviewers',
    'wallet',
    'payments',
    'subscriptions',
    'interviewer_subscriptions',
    'bookings',
    'candidates',
    'realtime',
    'feedbacks',
    'notifications',
    'ai_interviews',
    'issues',
    'progress',
    'admin_dashboard',

    'rest_framework',
    "channels",
    'corsheaders',
    'django_celery_results',
    "django_celery_beat",
    "rest_framework_simplejwt.token_blacklist",

]



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'authentication.authentication.CookieJWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # ADD THIS
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    
}




ASGI_APPLICATION = "intraview.asgi.application"



CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                (
                    os.getenv("REDIS_HOST", "redis"),
                    int(os.getenv("REDIS_PORT", 6379)),
                )
            ],
        },
    },
}




AUTH_USER_MODEL = 'authentication.CustomUser'





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'authentication.middleware.ClearExpiredJWTCookiesMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://localhost:5173"
)

CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    FRONTEND_URL,
]

# Cookie Security (Production Ready)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SAMESITE = (
    "None" if not DEBUG else "Lax"
)

CSRF_COOKIE_SAMESITE = (
    "None" if not DEBUG else "Lax"
)

# Reverse Proxy / HTTPS Settings
SECURE_PROXY_SSL_HEADER = (
    'HTTP_X_FORWARDED_PROTO',
    'https',
)

USE_X_FORWARDED_HOST = True

# Security Headers (Production Safe)

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = "DENY"

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


TAVUS_API_KEY = os.getenv("TAVUS_API_KEY", "")
TAVUS_AVATAR_ENABLED = _env_bool("TAVUS_AVATAR_ENABLED", default=False)
TAVUS_REPLICA_ID = os.getenv("TAVUS_REPLICA_ID", "").strip()
TAVUS_PERSONA_ID = os.getenv("TAVUS_PERSONA_ID", "").strip()
TAVUS_AVATAR_PARTICIPANT_IDENTITY = os.getenv(
    "TAVUS_AVATAR_PARTICIPANT_IDENTITY",
    "tavus-avatar-agent",
).strip()
TAVUS_AVATAR_PARTICIPANT_NAME = os.getenv(
    "TAVUS_AVATAR_PARTICIPANT_NAME",
    "AI Interviewer",
).strip()




ROOT_URLCONF = 'intraview.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'intraview.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases








# DATABASES = {
#   'default': {
#     'ENGINE': 'django.db.backends.postgresql',
#     'NAME': os.getenv("POSTGRES_DB"),
#     'USER': os.getenv("POSTGRES_USER"),
#     'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
#     'HOST': os.getenv("POSTGRES_HOST"),
#     'PORT': os.getenv("POSTGRES_PORT"),
#   }
# }


DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
TIME_ZONE = "Asia/Kolkata"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv("CLOUDINARY_CLOUD_NAME"),
    'API_KEY': os.getenv("CLOUDINARY_API_KEY"),
    'API_SECRET': os.getenv("CLOUDINARY_API_SECRET"),
}

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True,
)

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Required for cloudinary_storage compatibility
STATICFILES_STORAGE = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
)



STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Redis cache setup for OTP caching (Cache timeout 300s in code)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



# Celery configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = "django-db"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"







EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'                       # Gmail SMTP
EMAIL_PORT = 587                                    # TLS port
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER





SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}



GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")





DEFAULT_FROM_EMAIL = "intraview.website@gmail.com"


STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')






SENTRY_DSN = os.getenv("SENTRY_DSN")

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        traces_sample_rate=0.2,  # Performance tracing (safe)
        send_default_pii=True,   # User context (email, id)
        environment=os.getenv("ENVIRONMENT", "development"),
    )





# Minimum tokens to request payout
PAYOUT_MIN_TOKENS = 50

# Rate per token (in INR)
PAYOUT_RATE_PER_TOKEN = Decimal("10.00")

# Reference number prefix
PAYOUT_REFERENCE_PREFIX = "PAY"




ZEGO_APP_ID = int(os.getenv("ZEGO_APP_ID"))

ZEGO_SERVER_SECRET = os.getenv("ZEGO_SERVER_SECRET")

ZEGO_TOKEN_EXPIRY_SECONDS = int(
    os.getenv("ZEGO_TOKEN_EXPIRY_SECONDS", 7200)
)

ZEGO_EARLY_JOIN_MINUTES = int(
    os.getenv("ZEGO_EARLY_JOIN_MINUTES", 10)
)








NOVU_SECRET_KEY = os.environ.get("NOVU_SECRET_KEY", "")


# optional, if you ever need to override (defaults to https://api.novu.co in SDK)
NOVU_API_URL = os.environ.get("NOVU_API_URL", "https://api.novu.co")

# Map our internal EventType values to Novu workflow identifiers
NOVU_WORKFLOW_IDS = {
    # EventType.<NAME>.value : "workflowId in Novu"
    "INTERVIEW_BOOKED": "interview-booked",
    "PAYMENT_SUCCESS": "payment-success",
    "PAYOUT_FAILED": "payout-failed",
    "FEEDBACK_PENDING": "feedback-pending",
    "INTERVIEW_REMINDER_30M": "interview-reminder-30m",
    "RESCHEDULE_SLOT_REQUESTED": "reschedule-slot-requested",
    "FEEDBACK_SUBMITTED": "feedback-submitted",
    "ISSUE_RAISED": "issue-raised",
    "ISSUE_RESOLVED": "issue-resolved",
    "ISSUE_REJECTED": "issue-rejected",
    "ISSUE_ACTION_TAKEN": "issue-action-taken",
    "ISSUE_WAITING_RESPONSE": "issue-waiting-response",
}









LIVEKIT_URL = os.getenv("LIVEKIT_URL")
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY")
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET")





BACKEND_AGENT_SHARED_SECRET = os.getenv("BACKEND_AGENT_SHARED_SECRET", "change-me")



GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

GEMINI_EVALUATION_MODEL = os.getenv(
    "GEMINI_EVALUATION_MODEL",
    "gemini-2.5-flash",
)

GEMINI_FINAL_REPORT_MODEL = os.getenv(
    "GEMINI_FINAL_REPORT_MODEL",
    "gemini-2.5-pro",
)






LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },

    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },

    "django.request": {
        "handlers": ["console"],
        "level": "ERROR",
        "propagate": False,
    },
}
