# Generated by Django 5.2.7 on 2026-04-14 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INTERVIEW_BOOKED', 'INTERVIEW_BOOKED'), ('INTERVIEW_RESCHEDULED', 'INTERVIEW_RESCHEDULED'), ('INTERVIEW_CANCELLED', 'INTERVIEW_CANCELLED'), ('INTERVIEW_COMPLETED', 'INTERVIEW_COMPLETED'), ('PAYMENT_SUCCESS', 'PAYMENT_SUCCESS'), ('PAYOUT_FAILED', 'PAYOUT_FAILED'), ('FEEDBACK_PENDING', 'FEEDBACK_PENDING'), ('FEEDBACK_SUBMITTED', 'FEEDBACK_SUBMITTED')], db_index=True, max_length=64)),
                ('channel', models.CharField(choices=[('IN_APP', 'IN_APP'), ('EMAIL', 'EMAIL'), ('PUSH', 'PUSH'), ('SMS', 'SMS')], default='IN_APP', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], db_index=True, default='PENDING', max_length=16)),
                ('provider', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', help_text='Optional id for tying multiple notifications to one business operation (e.g. booking id).', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'status'], name='notificatio_event_t_d5ad3a_idx'), models.Index(fields=['recipient', 'status'], name='notificatio_recipie_cea552_idx'), models.Index(fields=['correlation_id'], name='notificatio_correla_755dec_idx')],
            },
        ),
    ]
