# Generated by Django 5.2.7 on 2026-04-19 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('INTERVIEW_BOOKED', 'INTERVIEW_BOOKED'), ('INTERVIEW_RESCHEDULED', 'INTERVIEW_RESCHEDULED'), ('INTERVIEW_CANCELLED', 'INTERVIEW_CANCELLED'), ('INTERVIEW_COMPLETED', 'INTERVIEW_COMPLETED'), ('PAYMENT_SUCCESS', 'PAYMENT_SUCCESS'), ('PAYOUT_FAILED', 'PAYOUT_FAILED'), ('FEEDBACK_PENDING', 'FEEDBACK_PENDING'), ('FEEDBACK_SUBMITTED', 'FEEDBACK_SUBMITTED'), ('INTERVIEW_REMINDER_30M', 'INTERVIEW_REMINDER_30M')], db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_514159_idx'),
        ),
    ]
