# Generated by Django 5.2.7 on 2026-04-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlog_is_read_notificationlog_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('INTERVIEW_BOOKED', 'INTERVIEW_BOOKED'), ('INTERVIEW_RESCHEDULED', 'INTERVIEW_RESCHEDULED'), ('INTERVIEW_CANCELLED', 'INTERVIEW_CANCELLED'), ('INTERVIEW_COMPLETED', 'INTERVIEW_COMPLETED'), ('PAYMENT_SUCCESS', 'PAYMENT_SUCCESS'), ('PAYOUT_FAILED', 'PAYOUT_FAILED'), ('FEEDBACK_PENDING', 'FEEDBACK_PENDING'), ('FEEDBACK_SUBMITTED', 'FEEDBACK_SUBMITTED'), ('INTERVIEW_REMINDER_30M', 'INTERVIEW_REMINDER_30M'), ('RESCHEDULE_SLOT_REQUESTED', 'RESCHEDULE_SLOT_REQUESTED')], db_index=True, max_length=64),
        ),
    ]
