# Generated by Django 5.2.7 on 2026-01-28 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('current_status', models.CharField(blank=True, max_length=50)),
                ('current_role', models.CharField(blank=True, max_length=120)),
                ('target_role', models.CharField(blank=True, max_length=120)),
                ('experience_level', models.CharField(blank=True, choices=[('FRESHER', 'Fresher'), ('JUNIOR', 'Junior (0-2 years)'), ('MID', 'Mid-Level (2-5 years)'), ('SENIOR', 'Senior (5+ years)')], max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('preferred_interview_types', models.JSONField(blank=True, default=list)),
                ('preferred_difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20)),
                ('preferred_duration', models.PositiveIntegerField(blank=True, default=30)),
                ('interviewer_notes', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='candidate_resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('resume_url', models.URLField(blank=True)),
                ('resume_upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='DONE', max_length=20)),
                ('resume_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completion', models.FloatField(default=0.0, editable=False)),
                ('interviews_completed', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Profile',
                'verbose_name_plural': 'Candidate Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
