# Generated by Django 5.2.7 on 2026-05-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidateprofile_bio_candidateprofile_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='ai_subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription-based AI quota expires.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='free_ai_interviews_remaining',
            field=models.PositiveIntegerField(default=3, help_text='Free onboarding AI interviews for new signups.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='has_unlimited_ai',
            field=models.BooleanField(default=False, help_text='True for Pro plan users — no quota or token deduction.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='subscription_ai_interviews_remaining',
            field=models.IntegerField(default=0, help_text='Remaining AI interview quota from paid subscription. -1 means unlimited (Pro).'),
        ),
    ]
