# Generated by Django 5.2.7 on 2026-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_add_ai_interview_quota_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Working Professional', 'Working Professional'), ('Freelancer', 'Freelancer'), ('Job Seeker', 'Job Seeker'), ('Career Switcher', 'Career Switcher')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
    ]
