# Generated by Django 5.2.7 on 2026-01-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='monthly_ai_used',
            field=models.PositiveIntegerField(default=0, help_text='AI interviews used in current billing cycle'),
        ),
    ]
