# Generated by Django 5.2.7 on 2026-01-19 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionpaymentorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpaymentorder',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpaymentorder',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpaymentorder',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpaymentorder',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='subscriptions.usersubscription'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpaymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount_inr__gt', 0)), name='subscription_amount_positive'),
        ),
    ]
