# Generated by Django 5.2.7 on 2026-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable role name, e.g. 'Software Engineer'.", max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier, auto-generated from name if blank.', max_length=160, unique=True)),
                ('category', models.CharField(blank=True, help_text="Optional category/group, e.g. 'Engineering', 'Data', 'Business'.", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional short description for UI/tooltips.')),
                ('aliases', models.JSONField(blank=True, default=list, help_text="List of alternative titles, e.g. ['SDE', 'Software Developer'].")),
                ('skills', models.JSONField(blank=True, default=list, help_text="List of key skills/tags, e.g. ['Python', 'Django', 'REST'].")),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Whether to show this role in the top 15 grid.')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Controls ordering of featured roles (lower first).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft toggle for deactivating roles without deleting data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'is_featured'], name='ai_intervie_is_acti_15f5aa_idx'), models.Index(fields=['category'], name='ai_intervie_categor_0b63b6_idx')],
            },
        ),
    ]
