# Generated by Django 5.2.7 on 2026-05-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('WARMUP', 'Warm-up'), ('BEHAVIORAL', 'Behavioral'), ('ROLE_RELATED', 'Role Related'), ('CODING', 'Coding')], max_length=32)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], max_length=32)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Planned interview duration (e.g. 5, 15, 30).')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('READY', 'Ready to Join'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='READY', max_length=20)),
                ('livekit_room_name', models.CharField(blank=True, help_text='Room name/ID used by LiveKit. Can be generated when joining.', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(help_text='The role this AI interview is targeted at.', on_delete=django.db.models.deletion.PROTECT, related_name='ai_interview_sessions', to='ai_interviews.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='ai_intervie_user_id_1902f6_idx'), models.Index(fields=['role', 'status'], name='ai_intervie_role_id_fbd157_idx')],
            },
        ),
    ]
