# Generated by Django 5.2.7 on 2026-05-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0002_aiinterviewsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewFinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='ai_interviews.aiinterviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='AIInterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='ai_interviews.aiinterviewsession')),
            ],
            options={
                'ordering': ['turn_index'],
            },
        ),
        migrations.CreateModel(
            name='AIInterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('confidence', models.CharField(blank=True, help_text='Optional model confidence label: low/medium/high.', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='ai_interviews.aiinterviewturn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='aiinterviewturn',
            constraint=models.UniqueConstraint(fields=('session', 'turn_index'), name='uniq_turn_per_session_index'),
        ),
    ]
