# Generated by Django 5.2.7 on 2026-05-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0003_aiinterviewfinalreport_aiinterviewturn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRuntimeState',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='runtime_state', serialize=False, to='ai_interviews.aiinterviewsession')),
                ('current_turn_index', models.PositiveIntegerField(default=0)),
                ('waiting_for_answer', models.BooleanField(default=False)),
                ('current_state', models.CharField(default='INITIALIZING', max_length=32)),
                ('current_question_id', models.CharField(blank=True, max_length=128)),
                ('remaining_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(auto_now=True)),
                ('reconnect_grace_until', models.DateTimeField(blank=True, null=True)),
                ('disconnect_count', models.PositiveIntegerField(default=0)),
                ('agent_session_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Interview runtime state',
                'verbose_name_plural': 'Interview runtime states',
            },
        ),
    ]
