# Generated by Django 5.2.7 on 2026-05-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0004_interviewruntimestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewruntimestate',
            name='active_runtime_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='interviewruntimestate',
            name='last_runtime_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewruntimestate',
            name='runtime_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewruntimestate',
            name='runtime_lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
