# Generated by Django 5.2.7 on 2026-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0005_interviewruntimestate_active_runtime_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinterviewevaluation',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aiinterviewevaluation',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aiinterviewevaluation',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aiinterviewfinalreport',
            name='areas_for_improvement',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aiinterviewfinalreport',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aiinterviewfinalreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='aiinterviewfinalreport',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
