# Generated by Django 5.2.7 on 2025-11-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_auth_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_otp_send_at',
            new_name='last_otp_sent_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Candidate'), ('interviewer', 'Interviewer'), ('admin', 'Admin'), ('company', 'Company')], default='user', max_length=20),
        ),
    ]
