# Generated by Django 5.2.7 on 2025-12-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_last_otp_send_at_customuser_last_otp_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interviewer_status',
            field=models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected'), ('APPROVED_NOT_ONBOARDED', 'Approved (Not Onboarded)'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='NOT_APPLIED', max_length=30),
        ),
    ]
