# Generated by Django 5.2.7 on 2026-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interviewer_warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
