# Generated by Django 5.2.7 on 2026-01-09 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price_inr', models.PositiveIntegerField(help_text='Monthly price in INR')),
                ('billing_cycle_days', models.PositiveIntegerField(default=30, help_text='Billing cycle length in days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_inr'],
            },
        ),
        migrations.CreateModel(
            name='InterviewerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('renewal_date', models.DateTimeField(blank=True, help_text='Next renewal date (Stripe-driven)', null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='interviewer_subscriptions.interviewersubscriptionplan')),
            ],
            options={
                'indexes': [models.Index(fields=['interviewer', 'status'], name='interviewer_intervi_1ddef3_idx'), models.Index(fields=['end_date'], name='interviewer_end_dat_40ef39_idx'), models.Index(fields=['stripe_subscription_id'], name='interviewer_stripe__d44fc9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('interviewer',), name='one_active_interviewer_subscription')],
            },
        ),
    ]
