# Generated by Django 5.2.7 on 2026-02-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_interviewbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('LIVE', 'Live'), ('ENDED', 'Ended'), ('ABORTED', 'Aborted'), ('NO_SHOW', 'No Show')], db_index=True, default='CREATED', max_length=20)),
                ('candidate_connected_at', models.DateTimeField(blank=True, null=True)),
                ('interviewer_connected_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('interviewer_disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reconnect_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='bookings.interviewbooking')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='realtime_in_status_d098d4_idx'), models.Index(fields=['booking'], name='realtime_in_booking_216b0d_idx')],
            },
        ),
    ]
