# Generated by Django 5.2.7 on 2026-03-04 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_interviewbooking_status'),
        ('realtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_note', to='bookings.interviewbooking')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interviewer Note',
                'verbose_name_plural': 'Interviewer Notes',
                'db_table': 'realtime_interviewer_note',
            },
        ),
    ]
