# Generated by Django 5.2.7 on 2026-03-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_interviewernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interviewer_finished',
            field=models.BooleanField(default=False),
        ),
    ]
