# Generated by Django 5.2.7 on 2026-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_interviewsession_candidate_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_total_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='evaluation_deadline',
            field=models.DateTimeField(blank=True, help_text='Last datetime when evaluations/reviews can be submitted.', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interviewer_total_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
