# Generated by Django 5.2.7 on 2026-01-09 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('locked_balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Wallet',
                'verbose_name_plural': 'Token Wallets',
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TOKEN_PURCHASE', 'Token Purchase'), ('BOOKING_LOCK', 'Booking Token Lock'), ('BOOKING_RELEASE', 'Booking Token Release'), ('SESSION_SPEND', 'Session Spent Tokens'), ('SESSION_EARN', 'Session Earned Tokens'), ('REFUND', 'Token Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=50)),
                ('amount', models.IntegerField(help_text='Positive or negative token amount depending on transaction')),
                ('balance_after', models.PositiveIntegerField(help_text='Wallet balance AFTER this transaction')),
                ('locked_balance_after', models.PositiveIntegerField(help_text='Locked balance AFTER this transaction')),
                ('reference_id', models.CharField(blank=True, help_text='External reference (booking_id, payment_id, etc.)', max_length=100, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.tokenwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('locked_balance__gte', 0)), name='locked_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_toke_wallet__66c434_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='wallet_toke_transac_0db2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['reference_id'], name='wallet_toke_referen_b4e73f_idx'),
        ),
    ]
