# Generated by Django 5.2.7 on 2026-01-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOKEN_PURCHASE', 'Token Purchase'), ('BOOKING_LOCK', 'Booking Token Lock'), ('BOOKING_RELEASE', 'Booking Token Release'), ('SESSION_SPEND', 'Session Spent Tokens'), ('SESSION_EARN', 'Session Earned Tokens'), ('REFUND', 'Token Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('SUBSCRIPTION_GRANT', 'Subscription Grant')], max_length=50),
        ),
    ]
