# Generated by Django 5.2.7 on 2026-01-31 13:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_tokentransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOKEN_PURCHASE', 'Token Purchase'), ('BOOKING_LOCK', 'Booking Token Lock'), ('BOOKING_RELEASE', 'Booking Token Release'), ('SESSION_SPEND', 'Session Spent Tokens'), ('SESSION_EARN', 'Session Earned Tokens'), ('REFUND', 'Token Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('SUBSCRIPTION_GRANT', 'Subscription Grant'), ('BOOKING_CANCEL_INTERVIEWER', 'Booking Cancel Interviewer'), ('PAYOUT_LOCK', 'Payout Token Lock'), ('PAYOUT_DEBIT', 'Payout Debit'), ('PAYOUT_UNLOCK', 'Payout Token Unlock')], max_length=50),
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, default=None, editable=False, max_length=50, unique=True)),
                ('tokens_requested', models.PositiveIntegerField(help_text='Number of tokens to payout (min 50)')),
                ('amount_inr', models.DecimalField(decimal_places=2, editable=False, help_text='Total amount in INR (calculated at request time)', max_digits=10)),
                ('token_rate_snapshot', models.DecimalField(decimal_places=2, editable=False, help_text='Rate per token at time of request (LOCKED)', max_digits=5)),
                ('bank_account_number', models.CharField(help_text='Bank account number (immutable)', max_length=50, validators=[django.core.validators.RegexValidator(message='Account must be 9-18 digits', regex='^\\d{9,18}$')])),
                ('ifsc_code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid IFSC format (e.g., SBIN0001234)', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('account_holder_name', models.CharField(help_text='Name as per bank account', max_length=100)),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid 10-digit mobile number', regex='^[6-9]\\d{9}$')])),
                ('verification_id_snapshot', models.CharField(blank=True, help_text='Verification ID at time of request', max_length=100)),
                ('verification_status_snapshot', models.CharField(blank=True, help_text='Verification status at time of request', max_length=50)),
                ('tokens_locked', models.BooleanField(default=False, help_text='Whether tokens are locked in wallet')),
                ('status', models.CharField(choices=[('REQUESTED', 'Pending Review'), ('APPROVED', 'Ready to Pay'), ('PAID', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='REQUESTED', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin comments during approval/rejection')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['interviewer', 'status'], name='wallet_payo_intervi_382fed_idx'), models.Index(fields=['status', '-requested_at'], name='wallet_payo_status_ecb4be_idx'), models.Index(fields=['reference_number'], name='wallet_payo_referen_027382_idx'), models.Index(fields=['processed_by'], name='wallet_payo_process_096c7c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tokens_requested__gte', 50)), name='min_50_tokens'), models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'APPROVED'])), fields=('interviewer',), name='unique_active_payout_per_interviewer')],
            },
        ),
    ]
