# Generated by Django 5.2.7 on 2026-05-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_tokentransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOKEN_PURCHASE', 'Token Purchase'), ('BOOKING_LOCK', 'Booking Token Lock'), ('BOOKING_RELEASE', 'Booking Token Release'), ('SESSION_SPEND', 'Session Spent Tokens'), ('SESSION_EARN', 'Session Earned Tokens'), ('REFUND', 'Token Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('SUBSCRIPTION_GRANT', 'Subscription Grant'), ('BOOKING_CANCEL_INTERVIEWER', 'Booking Cancel Interviewer'), ('COMPENSATION', 'Compensation'), ('PAYOUT_LOCK', 'Payout Token Lock'), ('PAYOUT_DEBIT', 'Payout Debit'), ('PAYOUT_UNLOCK', 'Payout Token Unlock')], max_length=50),
        ),
    ]
