# Generated by Django 5.2.7 on 2026-02-09 12:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_interviewbooking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('HUMAN', 'Human Interview'), ('AI', 'AI Interview')], db_index=True, default='HUMAN', max_length=10)),
                ('technical_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('problem_solving_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('confidence_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_score', models.DecimalField(decimal_places=1, editable=False, max_digits=3)),
                ('hire_recommendation', models.CharField(choices=[('STRONG_YES', 'Strong Yes'), ('YES', 'Yes'), ('MAYBE', 'Maybe'), ('NO', 'No'), ('STRONG_NO', 'Strong No')], max_length=20)),
                ('strengths', models.TextField()),
                ('areas_for_improvement', models.TextField()),
                ('actionable_suggestions', models.TextField()),
                ('additional_notes', models.TextField(blank=True)),
                ('interview_difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert')], max_length=20)),
                ('topics_covered', models.JSONField(default=list)),
                ('is_visible_to_candidate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_evaluation', to='bookings.interviewbooking')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'feedback_type'], name='feedbacks_c_candida_4e8035_idx'), models.Index(fields=['overall_score'], name='feedbacks_c_overall_9c1d6c_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking',), name='unique_evaluation_per_booking')],
            },
        ),
        migrations.CreateModel(
            name='InterviewerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('HUMAN', 'Human Interview'), ('AI', 'AI Interview')], db_index=True, default='HUMAN', max_length=10)),
                ('overall_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('was_interviewer_prepared', models.BooleanField()),
                ('was_feedback_helpful', models.BooleanField()),
                ('was_professional', models.BooleanField(default=True)),
                ('would_recommend', models.BooleanField()),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('reported_issues', models.JSONField(blank=True, default=list)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_review', to='bookings.interviewbooking')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['interviewer', 'overall_rating'], name='feedbacks_i_intervi_d8826a_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking',), name='unique_review_per_booking')],
            },
        ),
    ]
