# Generated by Django 5.2.7 on 2026-02-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateevaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
