# Generated by Django 5.2.7 on 2026-03-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_candidateevaluation_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewerreview',
            name='was_feedback_helpful',
        ),
    ]
