# Generated by Django 5.2.7 on 2026-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_remove_interviewerreview_was_feedback_helpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateevaluation',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
