# Generated by Django 5.2.7 on 2026-01-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviewers', '0003_intervieweravailability_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('token_cost', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CANCELLED_BY_CANDIDATE', 'Cancelled By Candidate'), ('CANCELLED_BY_INTERVIEWER', 'Cancelled By Interviewer')], default='PENDING', max_length=200)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='interviewers.intervieweravailability')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_bookings', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'status'], name='bookings_in_candida_c09c1a_idx'), models.Index(fields=['interviewer', 'status'], name='bookings_in_intervi_fe2264_idx'), models.Index(fields=['availability', 'status'], name='bookings_in_availab_b332eb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('token_cost__gt', 0)), name='booking_token_cost_positive')],
            },
        ),
    ]
