# Generated by Django 5.2.7 on 2026-01-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewbooking',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='reschedule_reason',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='rescheduled_by',
            field=models.CharField(blank=True, choices=[('CANDIDATE', 'Candidate'), ('INTERVIEWER', 'Interviewer')], max_length=20, null=True),
        ),
    ]
