# Generated by Django 5.2.7 on 2026-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_interviewbooking_reschedule_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CANCELLED_BY_CANDIDATE', 'Cancelled by Candidate'), ('CANCELLED_BY_INTERVIEWER', 'Cancelled by Interviewer'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=200),
        ),
    ]
