# Generated by Django 5.2.7 on 2026-03-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_interviewbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID_TO_INTERVIEWER', 'Paid to Interviewer'), ('REFUNDED_TO_CANDIDATE', 'Refunded to Candidate')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CANCELLED_BY_CANDIDATE', 'Cancelled by Candidate'), ('CANCELLED_BY_INTERVIEWER', 'Cancelled by Interviewer'), ('CANDIDATE_NO_SHOW', 'Candidate No Show'), ('INTERVIEWER_NO_SHOW', 'Interviewer No Show')], default='PENDING', max_length=200),
        ),
    ]
