# Generated by Django 5.2.7 on 2026-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_interviewbooking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID_TO_INTERVIEWER', 'Paid to Interviewer'), ('REFUNDED_TO_CANDIDATE', 'Refunded to Candidate'), ('AWAITING_EVALUATION', 'Awaiting Evaluation')], default='PENDING', max_length=100),
        ),
    ]
