# Generated by Django 5.2.7 on 2026-04-19 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_interviewbooking_evaluation_deadline'),
        ('interviewers', '0004_intervieweravailability_reschedule_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interviewbooking',
            index=models.Index(fields=['status', 'start_datetime'], name='bookings_in_status_0b5205_idx'),
        ),
    ]
