# Generated by Django 5.2.7 on 2026-04-25 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_interviewbooking_bookings_in_status_0b5205_idx'),
        ('interviewers', '0005_interviewerapplication_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewbooking',
            name='proposed_availability',
            field=models.ForeignKey(blank=True, help_text='Slot proposed by the candidate. Null = open preference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_bookings', to='interviewers.intervieweravailability'),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='reschedule_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='reschedule_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending Interviewer Action'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='NONE', help_text='NONE = no active request. PENDING = waiting for interviewer action. ACCEPTED/REJECTED = terminal states (reset to NONE after handled).', max_length=20),
        ),
        migrations.AddIndex(
            model_name='interviewbooking',
            index=models.Index(fields=['interviewer', 'reschedule_status'], name='bookings_in_intervi_847af4_idx'),
        ),
    ]
