# Generated by Django 5.2.7 on 2026-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_interviewbooking_proposed_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewbooking',
            name='candidate_goal',
            field=models.CharField(blank=True, choices=[('FIRST_MOCK', 'First Mock Interview'), ('PLACEMENT_PREP', 'Placement Preparation'), ('IMPROVE_CONFIDENCE', 'Improve Confidence'), ('COMPANY_PREP', 'Company Preparation'), ('PRACTICE_DSA', 'Practice DSA'), ('IMPROVE_COMM', 'Improve Communication'), ('GENERAL_PRACTICE', 'General Practice')], default='', help_text='What the candidate wants to achieve in this session.', max_length=30),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='candidate_notes',
            field=models.TextField(blank=True, help_text='Optional preparation notes from the candidate to the interviewer.', max_length=1000),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='', help_text='Target experience level (must be supported by interviewer).', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('TECHNICAL', 'Technical Interview'), ('BEHAVIORAL', 'Behavioral Interview'), ('HR_ROUND', 'HR Round'), ('CODING', 'Coding Interview'), ('MOCK_FULL', 'Mock Full Interview'), ('RESUME_REVIEW', 'Resume Review'), ('WARMUP', 'Warm-up Session'), ('SYSTEM_DESIGN', 'System Design')], default='', help_text='The type of interview the candidate wants.', max_length=30),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='selected_specialties',
            field=models.JSONField(blank=True, default=list, help_text="Subset of interviewer's specializations the candidate wants to focus on. Stored as a list of strings matching the interviewer's specializations field."),
        ),
    ]
